apiVersion: apps/v1
kind: Deployment
metadata:
    name: nodejs-deployment
    namespace: ingress-nginx
    labels:
        app: nodejs
spec:
    replicas: 3
    selector:
        matchLabels:
            app: nodejs
    template:
        metadata:
            labels:
                app: nodejs
                role: backend
        spec:
            containers:
                - name: nodejs
                  image: huyfst/nodejs
                  ports:
                      - containerPort: 3000
                  env:
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_PASSWORD
                                name: postgres-secret
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_USER
                                name: postgres-secret
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_DB
                                name: postgres-secret
                      - name: POSTGRES_HOST
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_HOST
                                name: postgres-secret
                      - name: POSTGRES_PORT
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_PORT
                                name: postgres-secret
                  resources:
                      limits:
                          cpu: 15m
                          memory: 100Mi
                      requests:
                          cpu: 5m
                          memory: 50Mi
            imagePullSecrets:
                - name: regcred
