apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    namespace: ingress-nginx
    labels:
        app: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres
                  ports:
                      - containerPort: 5432
                  env:
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_PASSWORD
                                name: postgres-secret
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_USER
                                name: postgres-secret
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                key: POSTGRES_DB
                                name: postgres-secret
                #   command:
                #       [
                #           "psql -U huyfst -d k8s -c 'CREATE TABLE k8s (name text);'",
                #           "psql -U huyfst -d k8s -c "INSERT INTO k8s (name) VALUES ('hello huy');"",
                #       ]
