apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc1
    namespace: ingress-nginx
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1Gi
    selector:
        matchLabels:
            type: local
