apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc2
    namespace: ingress-nginx
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 1Gi
    storageClassName: nfs
