apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: nfs
provisioner: nfs.csi.k8s.io
parameters:
    server: 172.20.0.5
    share: /
mountOptions:
    - nolock
volumeBindingMode: Immediate
